#!/bin/bash
FILES_DIR="/home/spectre256/documents/cycling/ride data/Garmin"
MOUNT_DIR="/media/GARMIN"

cd "${FILES_DIR}"

for file in $( ls ${MOUNT_DIR}/Garmin/History/*.tcx );
do
	#echo $file

	basename=`basename "$file"`
	#echo $basename
	if [ ! -f $basename ]
	then
		cp -v $file "${FILES_DIR}"
		pushd "${FILES_DIR}" > /dev/null
		git add "$basename"
		git commit "$basename" -m "adding ride file $basename"
		popd > /dev/null
	fi
done
