#!/bin/bash
#FILES_DIR="/run/media/spectre256/big/spectre256/repos/cycling/ride data/Garmin"
FILES_DIR="/home/spectre256/repos/cycling/ride data/Garmin"
MOUNT_DIR="/run/media/spectre256/GARMIN"

cd "${FILES_DIR}"

for file in $( ls ${MOUNT_DIR}/Garmin/History/*.tcx );
do
	#echo $file

	basename=`basename "$file"`
	#echo $basename
	if [ ! -f $basename ]
	then
		cp -v $file "${FILES_DIR}"
		pushd "${FILES_DIR}" > /dev/null
		git add "$basename"
		git commit "$basename" -m "Add ride file $basename"
		popd > /dev/null
	fi
done

for file in $( ls ${MOUNT_DIR}/Garmin/Activities/*.fit ); do
	basename=`basename "$file"`
	if [ ! -f $basename ]
	then
		cp -v $file "${FILES_DIR}"
		pushd "${FILES_DIR}" > /dev/null
		git add "$basename"
		git commit "$basename" -m "Add ride file $basename"
		popd > /dev/null
	fi
done
