#!/bin/bash

createTunnel() {
    /usr/bin/ssh -f -N -R 10022:localhost:22 -L19922:juliansimioni.com:27823  juliansimioni.com
    if [[ $? -eq 0 ]]; then
        echo Tunnel to hostb created successfully
    else
        echo An error occurred creating a tunnel to hostb RC was $?
    fi
}

/usr/bin/ssh -p 19922 localhost ls > /dev/null
if [[ $? -ne 0 ]]; then
	echo Creating new tunnel connection
	createTunnel
fi
