#!/bin/bash
if [ -d "/Users"]; then
	homeRepoDir=~/Documents/home #osx
else
	homeRepoDir=~/repos/home #linux
fi
dotfilesDir="${homeRepoDir}/dotfiles"

#ln command
ln="ln -nfs"

#create symlinks to commonly used directories
$ln ${homeRepoDir}/code/ ~/code
if [ -d "${homeRepoDir}/documents" ]; then
	$ln ${homeRepoDir}/documents/ ~/documents
fi

#symlink all dotfiles
for dotfile in ${dotfilesDir}/*
do
	dotfileName=$(basename $dotfile)
	$ln -b "${dotfile}" ~/.${dotfileName}
done


