#!/bin/bash

pictureDir=$1

# make symlinks
pushd $pictureDir

j=0
for i in `ls *.JPG`; do
	ln -s $i $j.jpg
	j=$((j+1))
done

popd

# make movie
avconv -r 15 -i $pictureDir/%d.jpg -s 2560x1920 -r 15 ${pictureDir}.mkv -threads 4

#unlink symlinks
pushd $pictureDir
for i in `ls *.jpg` do
	unlink $i
done
